apiVersion: v1
kind: Service
metadata:
  name: argo-rollouts-canary-service
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: rollouts-demo
---
apiVersion: v1
kind: Service
metadata:
  name: argo-rollouts-stable-service
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: rollouts-demo
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
  name: argo-rollouts-canary-service
  namespace: default
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
  name: argo-rollouts-stable-service
  namespace: default
