apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-guestbook-ui
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: custom-guestbook-ui
  template:
    metadata:
      labels:
        app: custom-guestbook-ui
    spec:
      containers:
        - image: argoproj/rollouts-demo:blue
          name: custom-guestbook-ui
          ports:
            - containerPort: 8080
